from __future__ import annotations

from typing import Any


def provider_registry() -> dict[str, list[dict[str, Any]]]:
    return {
        "market_data": [
            {
                "id": "akshare_market_data",
                "name": "AkShare Market Data",
                "status": "active",
                "markets": ["A-share", "HK", "US"],
                "auth": "none",
                "notes": "当前主行情适配器，受上游公开接口与网络可用性影响。",
            },
            {
                "id": "sina_a_share_market_data",
                "name": "Sina A-share Fallback",
                "status": "active",
                "markets": ["A-share"],
                "auth": "none",
                "notes": "A股实时/历史行情兜底接口。",
            },
            {
                "id": "tushare_market_data",
                "name": "Tushare Pro",
                "status": "reserved",
                "markets": ["A-share"],
                "auth": "api_key",
                "notes": "适合补全稳定日线、财务和指数数据，可能需要积分或付费权限。",
            },
            {
                "id": "duckdb_local_market_store",
                "name": "Local DuckDB Market Store",
                "status": "reserved",
                "markets": ["A-share", "HK", "US", "custom"],
                "auth": "local_file",
                "notes": "本地列式行情湖，适合长期 OHLCV、财务快照和事件特征缓存。",
            },
            {
                "id": "postgres_market_store",
                "name": "PostgreSQL Market Store",
                "status": "reserved",
                "markets": ["A-share", "HK", "US", "custom"],
                "auth": "database_url",
                "notes": "团队部署或多端同步时使用，可与 pgvector 扩展共存。",
            },
            {
                "id": "jqdata_market_data",
                "name": "JoinQuant/JQData",
                "status": "reserved",
                "markets": ["A-share"],
                "auth": "api_key",
                "notes": "适合机构级 A 股行情、行业和因子数据接入。",
            },
            {
                "id": "longport_market_data",
                "name": "LongPort OpenAPI",
                "status": "reserved",
                "markets": ["HK", "US"],
                "auth": "api_key",
                "notes": "后续可作为港股/美股行情与标的资料来源。",
            },
            {
                "id": "futu_openapi_market_data",
                "name": "Futu OpenAPI",
                "status": "reserved",
                "markets": ["HK", "US", "A-share"],
                "auth": "local_gateway",
                "notes": "需要本地 OpenD，适合实时行情增强。",
            },
            {
                "id": "alpha_vantage_market_data",
                "name": "Alpha Vantage",
                "status": "reserved",
                "markets": ["US", "FX", "macro"],
                "auth": "api_key",
                "notes": "美股、外汇和宏观时间序列接口，可作为美股行情辅助源。",
            },
            {
                "id": "fmp_market_data",
                "name": "Financial Modeling Prep",
                "status": "reserved",
                "markets": ["US", "ETF", "macro"],
                "auth": "api_key",
                "notes": "美股行情、财务、估值和新闻接口，适合与 yfinance 交叉校验。",
            },
            {
                "id": "yfinance_market_data",
                "name": "yfinance Auxiliary Check",
                "status": "reserved",
                "markets": ["US", "HK", "ETF"],
                "auth": "none",
                "notes": "非官方 Yahoo Finance 包，适合辅助校验，不建议作为唯一生产数据源。",
            },
            {
                "id": "polygon_market_data",
                "name": "Polygon.io",
                "status": "reserved",
                "markets": ["US", "options", "crypto", "FX"],
                "auth": "api_key",
                "notes": "高质量美股/期权/加密/外汇行情，适合更实时的数据层。",
            },
            {
                "id": "intrinio_market_data",
                "name": "Intrinio",
                "status": "reserved",
                "markets": ["US", "global"],
                "auth": "api_key",
                "notes": "机构级基本面、行情和公司数据，需要授权套餐。",
            },
            {
                "id": "wind_terminal_data",
                "name": "Wind",
                "status": "reserved",
                "markets": ["A-share", "HK", "US", "macro", "fixed_income", "fund"],
                "auth": "licensed_terminal_or_api",
                "notes": "机构级数据源，接入前需要确认 WindPy 或企业 API 授权。",
            },
            {
                "id": "choice_terminal_data",
                "name": "Choice",
                "status": "reserved",
                "markets": ["A-share", "HK", "US", "fund", "macro"],
                "auth": "licensed_terminal_or_api",
                "notes": "东方财富 Choice 终端/API 预留接口，需要授权环境。",
            },
            {
                "id": "ifind_terminal_data",
                "name": "iFinD",
                "status": "reserved",
                "markets": ["A-share", "HK", "US", "fund", "macro"],
                "auth": "licensed_terminal_or_api",
                "notes": "同花顺 iFinD 终端/API 预留接口，需要授权环境。",
            },
            {
                "id": "local_csv_market_data",
                "name": "Local CSV/Excel Import",
                "status": "reserved",
                "markets": ["A-share", "HK", "US", "custom"],
                "auth": "local_file",
                "notes": "Local-first 手动导入通道。",
            },
        ],
        "information": [
            {
                "id": "rss_news",
                "name": "RSS News",
                "status": "active",
                "types": ["news"],
                "auth": "none",
                "notes": "适合低成本新闻同步，不保证秒级实时。",
            },
            {
                "id": "sina_finance_rollnews",
                "name": "Sina Finance Roll News",
                "status": "active",
                "types": ["news"],
                "auth": "none",
                "notes": "当前新闻兜底适配器。",
            },
            {
                "id": "cninfo_disclosure",
                "name": "CNINFO Disclosure",
                "status": "active",
                "types": ["announcement", "financial_report"],
                "auth": "none",
                "notes": "A股公告与财报披露来源。",
            },
            {
                "id": "hkexnews_disclosure",
                "name": "HKEXnews Disclosure",
                "status": "active",
                "types": ["announcement", "financial_report"],
                "auth": "none",
                "notes": "港股披露易公告/财报适配器首版。",
            },
            {
                "id": "eastmoney_news",
                "name": "Eastmoney News/Notice",
                "status": "reserved",
                "types": ["news", "announcement"],
                "auth": "none_or_cookie",
                "notes": "后续可补行业新闻、公告镜像和研报摘要。",
            },
            {
                "id": "finnhub_news",
                "name": "Finnhub News",
                "status": "reserved",
                "types": ["news", "company_news", "earnings_calendar"],
                "auth": "api_key",
                "notes": "美股公司新闻、公告日历和情绪类数据源。",
            },
            {
                "id": "fmp_news",
                "name": "FMP News",
                "status": "reserved",
                "types": ["news", "press_release", "earnings"],
                "auth": "api_key",
                "notes": "与 FMP 行情/基本面接口配套的美股新闻源。",
            },
            {
                "id": "chinese_finance_scraper",
                "name": "Chinese Finance Website Scraper",
                "status": "reserved",
                "types": ["news", "announcement_mirror", "industry_news"],
                "auth": "none_or_cookie",
                "notes": "中文财经网站非官方抓取预留层，需遵守 robots、频率限制和版权要求。",
            },
            {
                "id": "research_report_provider",
                "name": "Research Report Provider",
                "status": "reserved",
                "types": ["research_report"],
                "auth": "licensed_api",
                "notes": "研报通常涉及授权，接入前需要确认数据许可。",
            },
            {
                "id": "policy_rss_provider",
                "name": "Policy RSS/Web Adapter",
                "status": "reserved",
                "types": ["policy"],
                "auth": "none",
                "notes": "用于监管、部委、交易所政策事件同步。",
            },
            {
                "id": "mcp_finance_provider",
                "name": "MCP Finance Provider",
                "status": "reserved",
                "types": ["market_data", "news", "knowledge_graph"],
                "auth": "tool_config",
                "notes": "预留 MCP 工具接入方式。",
            },
        ],
    }
